AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4

Style/DoubleNegation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - faraday-http.gemspec
