AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Style/DoubleNegation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - faraday-http.gemspec

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

